<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CategoryController extends CoreController
{
    public function index(Request $request): JsonResponse
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
